### ISSUE TITLE
Python3.8 breaking

### ISSUE THREAD

**Issue by jorxster** [muety/website-watcher#8]
This used to work on python3.7, but I moved to an OS which runs python3.8. Now I get this:

$ python3 watcher.py -u https://www.thisworddoesnotexist.com --adapter email -r EXAMPLE@gmail.com -s EXAMPLE@gmail.com --subject "EXAMPLE" --smtp_username EXAMPLE@gmail.com --smtp_password EXAMPLE --smtp
```

> /media/jorxster/NTFS_2/1_GIT/website-watcher-script/adapters/email.py(34)send()
-> smtp = smtplib.SMTP(self.args.smtp_host, self.args.smtp_port)
Traceback (most recent call last):
  File "watcher.py", line 90, in <module>
    main(*parser.parse_known_args())
  File "watcher.py", line 68, in main
    ok = adapter.send('Difference is %s characters.\n%s' % (str(diff), args.url))
  File "/media/jorxster/NTFS_2/1_GIT/website-watcher-script/adapters/email.py", line 34, in send
    smtp = smtplib.SMTP(self.args.smtp_host, self.args.smtp_port)
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

cheers,
Jordan

**Comment by muety** [comment]
Sorry for the (very) delayed answer. I was busy with other projects, but I'll start investigating now! Does the problem still exist?

**Comment by muety** [comment]
Looks like you are missing the `--smtp_host` argument. Passing it to the command should solve your problem. Otherwise, please re-open the issue.
